//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

namespace Dqe.Domain.Model.Wt
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Estimate
    {

        private string estimateIdField;

        private string descriptionField;

        private UnitSystemType unitSystemField;

        private string specYearField;

        private string countyField;

        private string urbanRuralTypeField;

        private EstimateEstimateBreakdown[] estimateBreakdownField;

        private EstimateFund[] fundField;

        private EstimateEstimateGroup[] estimateGroupField;

        /// <remarks/>
        public string EstimateId
        {
            get
            {
                return this.estimateIdField;
            }
            set
            {
                this.estimateIdField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public UnitSystemType UnitSystem
        {
            get
            {
                return this.unitSystemField;
            }
            set
            {
                this.unitSystemField = value;
            }
        }

        /// <remarks/>
        public string SpecYear
        {
            get
            {
                return this.specYearField;
            }
            set
            {
                this.specYearField = value;
            }
        }

        /// <remarks/>
        public string County
        {
            get
            {
                return this.countyField;
            }
            set
            {
                this.countyField = value;
            }
        }

        /// <remarks/>
        public string UrbanRuralType
        {
            get
            {
                return this.urbanRuralTypeField;
            }
            set
            {
                this.urbanRuralTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EstimateBreakdown")]
        public EstimateEstimateBreakdown[] EstimateBreakdown
        {
            get
            {
                return this.estimateBreakdownField;
            }
            set
            {
                this.estimateBreakdownField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Fund")]
        public EstimateFund[] Fund
        {
            get
            {
                return this.fundField;
            }
            set
            {
                this.fundField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EstimateGroup")]
        public EstimateEstimateGroup[] EstimateGroup
        {
            get
            {
                return this.estimateGroupField;
            }
            set
            {
                this.estimateGroupField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum UnitSystemType
    {

        /// <remarks/>
        E,

        /// <remarks/>
        M,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Item,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class EstimateEstimateBreakdown
    {

        private string breakdown_IDField;

        private string descriptionField;

        private string breakdowntypeField;

        private string bdcde1Field;

        private string bdcde2Field;

        private string bddt1Field;

        private string bddt2Field;

        private string bdflg1Field;

        private string bdflg2Field;

        private string bdnum1Field;

        private string bdnum2Field;

        private string bdsst1Field;

        private string bdsst2Field;

        /// <remarks/>
        public string Breakdown_ID
        {
            get
            {
                return this.breakdown_IDField;
            }
            set
            {
                this.breakdown_IDField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string Breakdowntype
        {
            get
            {
                return this.breakdowntypeField;
            }
            set
            {
                this.breakdowntypeField = value;
            }
        }

        /// <remarks/>
        public string bdcde1
        {
            get
            {
                return this.bdcde1Field;
            }
            set
            {
                this.bdcde1Field = value;
            }
        }

        /// <remarks/>
        public string bdcde2
        {
            get
            {
                return this.bdcde2Field;
            }
            set
            {
                this.bdcde2Field = value;
            }
        }

        /// <remarks/>
        public string bddt1
        {
            get
            {
                return this.bddt1Field;
            }
            set
            {
                this.bddt1Field = value;
            }
        }

        /// <remarks/>
        public string bddt2
        {
            get
            {
                return this.bddt2Field;
            }
            set
            {
                this.bddt2Field = value;
            }
        }

        /// <remarks/>
        public string bdflg1
        {
            get
            {
                return this.bdflg1Field;
            }
            set
            {
                this.bdflg1Field = value;
            }
        }

        /// <remarks/>
        public string bdflg2
        {
            get
            {
                return this.bdflg2Field;
            }
            set
            {
                this.bdflg2Field = value;
            }
        }

        /// <remarks/>
        public string bdnum1
        {
            get
            {
                return this.bdnum1Field;
            }
            set
            {
                this.bdnum1Field = value;
            }
        }

        /// <remarks/>
        public string bdnum2
        {
            get
            {
                return this.bdnum2Field;
            }
            set
            {
                this.bdnum2Field = value;
            }
        }

        /// <remarks/>
        public string bdsst1
        {
            get
            {
                return this.bdsst1Field;
            }
            set
            {
                this.bdsst1Field = value;
            }
        }

        /// <remarks/>
        public string bdsst2
        {
            get
            {
                return this.bdsst2Field;
            }
            set
            {
                this.bdsst2Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class EstimateFund
    {

        private string jobFundCodeField;

        private string jobFundDescriptionField;

        private string jobFundPriorityField;

        private string jobFundFedFlagField;

        private decimal jobFundPctField;

        private bool jobFundPctFieldSpecified;

        private string jobFundLimitField;

        private bool jobFundLimitFieldSpecified;

        private string jobFundGroupField;

        private string jobFundFacsCodeField;

        private string fundPackageField;

        /// <remarks/>
        public string JobFundCode
        {
            get
            {
                return this.jobFundCodeField;
            }
            set
            {
                this.jobFundCodeField = value;
            }
        }

        /// <remarks/>
        public string JobFundDescription
        {
            get
            {
                return this.jobFundDescriptionField;
            }
            set
            {
                this.jobFundDescriptionField = value;
            }
        }

        /// <remarks/>
        public string JobFundPriority
        {
            get
            {
                return this.jobFundPriorityField;
            }
            set
            {
                this.jobFundPriorityField = value;
            }
        }

        /// <remarks/>
        public string JobFundFedFlag
        {
            get
            {
                return this.jobFundFedFlagField;
            }
            set
            {
                this.jobFundFedFlagField = value;
            }
        }

        /// <remarks/>
        public decimal JobFundPct
        {
            get
            {
                return this.jobFundPctField;
            }
            set
            {
                this.jobFundPctField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JobFundPctSpecified
        {
            get
            {
                return this.jobFundPctFieldSpecified;
            }
            set
            {
                this.jobFundPctFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string JobFundLimit
        {
            get
            {
                return this.jobFundLimitField;
            }
            set
            {
                this.jobFundLimitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JobFundLimitSpecified
        {
            get
            {
                return this.jobFundLimitFieldSpecified;
            }
            set
            {
                this.jobFundLimitFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string JobFundGroup
        {
            get
            {
                return this.jobFundGroupField;
            }
            set
            {
                this.jobFundGroupField = value;
            }
        }

        /// <remarks/>
        public string JobFundFacsCode
        {
            get
            {
                return this.jobFundFacsCodeField;
            }
            set
            {
                this.jobFundFacsCodeField = value;
            }
        }

        /// <remarks/>
        public string FundPackage
        {
            get
            {
                return this.fundPackageField;
            }
            set
            {
                this.fundPackageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class EstimateEstimateGroup
    {

        private string groupNumberField;

        private string descriptionField;

        private string alternateCodeField;

        private EstimateEstimateGroupEstimateItem[] estimateItemField;

        private EstimateEstimateGroupEstimateFund[] estimateFundField;

        /// <remarks/>
        public string GroupNumber
        {
            get
            {
                return this.groupNumberField;
            }
            set
            {
                this.groupNumberField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string AlternateCode
        {
            get
            {
                return this.alternateCodeField;
            }
            set
            {
                this.alternateCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EstimateItem")]
        public EstimateEstimateGroupEstimateItem[] EstimateItem
        {
            get
            {
                return this.estimateItemField;
            }
            set
            {
                this.estimateItemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EstimateFund")]
        public EstimateEstimateGroupEstimateFund[] EstimateFund
        {
            get
            {
                return this.estimateFundField;
            }
            set
            {
                this.estimateFundField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class EstimateEstimateGroupEstimateItem
    {

        private string lineNumberField;

        private string itemCodeField;

        private string descriptionField;

        private string supplementalDescriptionField;

        private string commentField;

        private string alternateCodeField;

        private string isAdHocPriceField;

        private object quantityField;

        private object unitPriceField;

        private object unitPriceUnfinishedField;

        private string isPriceLockedField;

        private EstimateEstimateGroupEstimateItemEstimateBreakItem[] estimateBreakItemField;

        private string fundPackageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string LineNumber
        {
            get
            {
                return this.lineNumberField;
            }
            set
            {
                this.lineNumberField = value;
            }
        }

        /// <remarks/>
        public string ItemCode
        {
            get
            {
                return this.itemCodeField;
            }
            set
            {
                this.itemCodeField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string SupplementalDescription
        {
            get
            {
                return this.supplementalDescriptionField;
            }
            set
            {
                this.supplementalDescriptionField = value;
            }
        }

        /// <remarks/>
        public string Comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        /// <remarks/>
        public string AlternateCode
        {
            get
            {
                return this.alternateCodeField;
            }
            set
            {
                this.alternateCodeField = value;
            }
        }

        /// <remarks/>
        public string IsAdHocPrice
        {
            get
            {
                return this.isAdHocPriceField;
            }
            set
            {
                this.isAdHocPriceField = value;
            }
        }

        /// <remarks/>
        public object Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }

        /// <remarks/>
        public object UnitPrice
        {
            get
            {
                return this.unitPriceField;
            }
            set
            {
                this.unitPriceField = value;
            }
        }

        /// <remarks/>
        public object UnitPriceUnfinished
        {
            get
            {
                return this.unitPriceUnfinishedField;
            }
            set
            {
                this.unitPriceUnfinishedField = value;
            }
        }

        /// <remarks/>
        public string IsPriceLocked
        {
            get
            {
                return this.isPriceLockedField;
            }
            set
            {
                this.isPriceLockedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EstimateBreakItem")]
        public EstimateEstimateGroupEstimateItemEstimateBreakItem[] EstimateBreakItem
        {
            get
            {
                return this.estimateBreakItemField;
            }
            set
            {
                this.estimateBreakItemField = value;
            }
        }

        /// <remarks/>
        public string FundPackage
        {
            get
            {
                return this.fundPackageField;
            }
            set
            {
                this.fundPackageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class EstimateEstimateGroupEstimateItemEstimateBreakItem
    {

        private string ilinenoField;

        private string breakdown_IDField;

        private string breakdownitem_linenumField;

        private object quantityField;

        private string commentsField;

        private string bicde1Field;

        private string bicde2Field;

        private string bidt1Field;

        private string bidt2Field;

        private string biflg1Field;

        private string biflg2Field;

        private string binum1Field;

        private string binum2Field;

        private string bisst1Field;

        private string bisst2Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string ilineno
        {
            get
            {
                return this.ilinenoField;
            }
            set
            {
                this.ilinenoField = value;
            }
        }

        /// <remarks/>
        public string Breakdown_ID
        {
            get
            {
                return this.breakdown_IDField;
            }
            set
            {
                this.breakdown_IDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string Breakdownitem_linenum
        {
            get
            {
                return this.breakdownitem_linenumField;
            }
            set
            {
                this.breakdownitem_linenumField = value;
            }
        }

        /// <remarks/>
        public object Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }

        /// <remarks/>
        public string Comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }

        /// <remarks/>
        public string bicde1
        {
            get
            {
                return this.bicde1Field;
            }
            set
            {
                this.bicde1Field = value;
            }
        }

        /// <remarks/>
        public string bicde2
        {
            get
            {
                return this.bicde2Field;
            }
            set
            {
                this.bicde2Field = value;
            }
        }

        /// <remarks/>
        public string bidt1
        {
            get
            {
                return this.bidt1Field;
            }
            set
            {
                this.bidt1Field = value;
            }
        }

        /// <remarks/>
        public string bidt2
        {
            get
            {
                return this.bidt2Field;
            }
            set
            {
                this.bidt2Field = value;
            }
        }

        /// <remarks/>
        public string biflg1
        {
            get
            {
                return this.biflg1Field;
            }
            set
            {
                this.biflg1Field = value;
            }
        }

        /// <remarks/>
        public string biflg2
        {
            get
            {
                return this.biflg2Field;
            }
            set
            {
                this.biflg2Field = value;
            }
        }

        /// <remarks/>
        public string binum1
        {
            get
            {
                return this.binum1Field;
            }
            set
            {
                this.binum1Field = value;
            }
        }

        /// <remarks/>
        public string binum2
        {
            get
            {
                return this.binum2Field;
            }
            set
            {
                this.binum2Field = value;
            }
        }

        /// <remarks/>
        public string bisst1
        {
            get
            {
                return this.bisst1Field;
            }
            set
            {
                this.bisst1Field = value;
            }
        }

        /// <remarks/>
        public string bisst2
        {
            get
            {
                return this.bisst2Field;
            }
            set
            {
                this.bisst2Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class EstimateEstimateGroupEstimateFund
    {

        private string jobFundCodeField;

        private string jobFundDescriptionField;

        private string jobFundPriorityField;

        private string jobFundFedFlagField;

        private decimal jobFundPctField;

        private bool jobFundPctFieldSpecified;

        private string jobFundLimitField;

        private bool jobFundLimitFieldSpecified;

        private string jobFundGroupField;

        private string jobFundFacsCodeField;

        /// <remarks/>
        public string JobFundCode
        {
            get
            {
                return this.jobFundCodeField;
            }
            set
            {
                this.jobFundCodeField = value;
            }
        }

        /// <remarks/>
        public string JobFundDescription
        {
            get
            {
                return this.jobFundDescriptionField;
            }
            set
            {
                this.jobFundDescriptionField = value;
            }
        }

        /// <remarks/>
        public string JobFundPriority
        {
            get
            {
                return this.jobFundPriorityField;
            }
            set
            {
                this.jobFundPriorityField = value;
            }
        }

        /// <remarks/>
        public string JobFundFedFlag
        {
            get
            {
                return this.jobFundFedFlagField;
            }
            set
            {
                this.jobFundFedFlagField = value;
            }
        }

        /// <remarks/>
        public decimal JobFundPct
        {
            get
            {
                return this.jobFundPctField;
            }
            set
            {
                this.jobFundPctField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JobFundPctSpecified
        {
            get
            {
                return this.jobFundPctFieldSpecified;
            }
            set
            {
                this.jobFundPctFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string JobFundLimit
        {
            get
            {
                return this.jobFundLimitField;
            }
            set
            {
                this.jobFundLimitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JobFundLimitSpecified
        {
            get
            {
                return this.jobFundLimitFieldSpecified;
            }
            set
            {
                this.jobFundLimitFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string JobFundGroup
        {
            get
            {
                return this.jobFundGroupField;
            }
            set
            {
                this.jobFundGroupField = value;
            }
        }

        /// <remarks/>
        public string JobFundFacsCode
        {
            get
            {
                return this.jobFundFacsCodeField;
            }
            set
            {
                this.jobFundFacsCodeField = value;
            }
        }
    }
}