//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dqe.Infrastructure.WtEstimatorService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/Validation")]
    [System.SerializableAttribute()]
    public partial class OperationFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ExceptionMessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dqe.Infrastructure.WtEstimatorService.OperationMessage[] MessagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ExceptionMessages {
            get {
                return this.ExceptionMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessagesField, value) != true)) {
                    this.ExceptionMessagesField = value;
                    this.RaisePropertyChanged("ExceptionMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dqe.Infrastructure.WtEstimatorService.OperationMessage[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationMessage", Namespace="http://schemas.datacontract.org/2004/07/Validation")]
    [System.SerializableAttribute()]
    public partial class OperationMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasBeenLoggedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dqe.Infrastructure.WtEstimatorService.OperationMessage.MessageLevels MessageLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dqe.Infrastructure.WtEstimatorService.OperationMessage.MessageTypes MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ModelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasBeenLogged {
            get {
                return this.HasBeenLoggedField;
            }
            set {
                if ((this.HasBeenLoggedField.Equals(value) != true)) {
                    this.HasBeenLoggedField = value;
                    this.RaisePropertyChanged("HasBeenLogged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dqe.Infrastructure.WtEstimatorService.OperationMessage.MessageLevels MessageLevel {
            get {
                return this.MessageLevelField;
            }
            set {
                if ((this.MessageLevelField.Equals(value) != true)) {
                    this.MessageLevelField = value;
                    this.RaisePropertyChanged("MessageLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dqe.Infrastructure.WtEstimatorService.OperationMessage.MessageTypes MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((this.MessageTypeField.Equals(value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ModelId {
            get {
                return this.ModelIdField;
            }
            set {
                if ((this.ModelIdField.Equals(value) != true)) {
                    this.ModelIdField = value;
                    this.RaisePropertyChanged("ModelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelName {
            get {
                return this.ModelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelNameField, value) != true)) {
                    this.ModelNameField = value;
                    this.RaisePropertyChanged("ModelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortMessage {
            get {
                return this.ShortMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortMessageField, value) != true)) {
                    this.ShortMessageField = value;
                    this.RaisePropertyChanged("ShortMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="OperationMessage.MessageLevels", Namespace="http://schemas.datacontract.org/2004/07/Validation")]
        public enum MessageLevels : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Error = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Warning = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Information = 2,
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="OperationMessage.MessageTypes", Namespace="http://schemas.datacontract.org/2004/07/Validation")]
        public enum MessageTypes : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Concurrency = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            General = 1,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportOptions", Namespace="http://schemas.datacontract.org/2004/07/Utils")]
    public enum ImportOptions : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UpdateIgnore = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UpdateOverwrite = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeleteItems = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeleteProjects = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WtEstimatorService.IEstimatorService")]
    public interface IEstimatorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstimatorService/CheckOutProposal", ReplyAction="http://tempuri.org/IEstimatorService/CheckOutProposalResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dqe.Infrastructure.WtEstimatorService.OperationFault), Action="http://tempuri.org/IEstimatorService/CheckOutProposalOperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/Validation")]
        string CheckOutProposal(string proposalName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstimatorService/ExportProposal", ReplyAction="http://tempuri.org/IEstimatorService/ExportProposalResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dqe.Infrastructure.WtEstimatorService.OperationFault), Action="http://tempuri.org/IEstimatorService/ExportProposalOperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/Validation")]
        string ExportProposal(string proposalName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstimatorService/CheckInProposal", ReplyAction="http://tempuri.org/IEstimatorService/CheckInProposalResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dqe.Infrastructure.WtEstimatorService.OperationFault), Action="http://tempuri.org/IEstimatorService/CheckInProposalOperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/Validation")]
        string CheckInProposal(byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstimatorService/ImportProject", ReplyAction="http://tempuri.org/IEstimatorService/ImportProjectResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dqe.Infrastructure.WtEstimatorService.OperationFault), Action="http://tempuri.org/IEstimatorService/ImportProjectOperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/Validation")]
        void ImportProject(byte[] importData, Dqe.Infrastructure.WtEstimatorService.ImportOptions options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstimatorService/CheckOutProject", ReplyAction="http://tempuri.org/IEstimatorService/CheckOutProjectResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dqe.Infrastructure.WtEstimatorService.OperationFault), Action="http://tempuri.org/IEstimatorService/CheckOutProjectOperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/Validation")]
        string CheckOutProject(string projectName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstimatorService/ExportProject", ReplyAction="http://tempuri.org/IEstimatorService/ExportProjectResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dqe.Infrastructure.WtEstimatorService.OperationFault), Action="http://tempuri.org/IEstimatorService/ExportProjectOperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/Validation")]
        string ExportProject(string projectName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEstimatorServiceChannel : Dqe.Infrastructure.WtEstimatorService.IEstimatorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EstimatorServiceClient : System.ServiceModel.ClientBase<Dqe.Infrastructure.WtEstimatorService.IEstimatorService>, Dqe.Infrastructure.WtEstimatorService.IEstimatorService {
        
        public EstimatorServiceClient() {
        }
        
        public EstimatorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EstimatorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstimatorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstimatorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckOutProposal(string proposalName) {
            return base.Channel.CheckOutProposal(proposalName);
        }
        
        public string ExportProposal(string proposalName) {
            return base.Channel.ExportProposal(proposalName);
        }
        
        public string CheckInProposal(byte[] data) {
            return base.Channel.CheckInProposal(data);
        }
        
        public void ImportProject(byte[] importData, Dqe.Infrastructure.WtEstimatorService.ImportOptions options) {
            base.Channel.ImportProject(importData, options);
        }
        
        public string CheckOutProject(string projectName) {
            return base.Channel.CheckOutProject(projectName);
        }
        
        public string ExportProject(string projectName) {
            return base.Channel.ExportProject(projectName);
        }
    }
}
