namespace Dqe.Domain.Model
{
    public enum PrimaryUnitType
    {
        NotSet = 0,
        Acre = 1,
        Assembly = 2,
        CubicFoot = 3,
        CubicYard = 4,
        Day = 5,
        DollarsPerDay = 6,
        Each = 7,
        EachDay = 8,
        Gallon = 9,
        GrossMile = 10,
        Hour = 11,
        Pound = 12,
        Foot = 13,
        Location = 14,
        LumpSum = 15,
        Luminaire = 16,
        ThouBoardMeasure = 17,
        ManHour = 18,
        Mile = 19,
        ThouGallons = 20,
        Month = 21,
        NetMile = 22,
        PerAnalysis = 23,
        PerBuilding = 24,
        PerIntersection = 25,
        Plant = 26,
        PerMile = 27,
        PerSet = 28,
        PerWell = 29,
        SquareFoot = 30,
        SquareYard = 31,
        Therms = 32,
        Ton = 33,
        Yard = 34,
    }
}