namespace Dqe.Domain.Model
{
    public enum SecondaryUnitType
    {
        None = 0,
        AC = 1,
        AS = 2,
        CF = 3,
        CY = 4,
        DA = 5,
        DD = 6,
        EA = 7,
        ED = 8,
        GA = 9,
        GM = 10,
        HR = 11,
        LB = 12,
        LF = 13,
        LO = 14,
        LS = 15,
        LU = 16,
        MB = 17,
        MH = 18,
        MI = 19,
        MG = 20,
        MO = 21,
        NM = 22,
        PA = 23,
        PB = 24,
        PI = 25,
        PL = 26,
        PM = 27,
        PS = 28,
        PW = 29,
        SF = 30,
        SY = 31,
        TH = 32,
        TN = 33,
        YD = 34,
    }
}